# Generated by Django 5.2.9 on 2026-02-02 01:41

import django.core.validators
import lectorqr.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Código interno')),
                ('id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El ID debe ser alfanumérico y tener máximo 10 caracteres.', regex='^[A-Za-z0-9]{1,10}$')], verbose_name='ID QR')),
                ('nombre', lectorqr.fields.EncryptedTextField(verbose_name='Nombre')),
                ('fecha_nacimiento', lectorqr.fields.EncryptedDateField(verbose_name='Fecha de nacimiento')),
                ('email', lectorqr.fields.EncryptedTextField(verbose_name='Correo electrónico')),
                ('telefono', lectorqr.fields.EncryptedTextField(verbose_name='Teléfono')),
                ('fecha_de_registro', lectorqr.fields.EncryptedDateField(verbose_name='Fecha de registro')),
                ('texto', lectorqr.fields.EncryptedTextField(verbose_name='Texto')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='images/perfil/')),
                ('foto_resultado', models.ImageField(blank=True, null=True, upload_to='results/resultado/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alumnos',
                'ordering': ['-codigo'],
            },
        ),
    ]
