# Generated by Django 5.2.9 on 2026-02-04 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectorqr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='lectorqr.alumno', verbose_name='Alumno Escaneado')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to=settings.AUTH_USER_MODEL, verbose_name='Escaneado por')),
            ],
            options={
                'verbose_name': 'Registro de Escaneo',
                'verbose_name_plural': 'Registros de Escaneos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
